//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAOCAO
    {
        public int THANG { get; set; }
        public int LOAIPHONG { get; set; }
        public Nullable<int> DOANHTHU { get; set; }
        public Nullable<double> TYLE { get; set; }
    }
}
