//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTHD
    {
        public string MACTHD { get; set; }
        public string MAHD { get; set; }
        public string MAPHONG { get; set; }
        public int SONGAYTHUE { get; set; }
        public int THANHTIEN { get; set; }
    
        public virtual HOADON HOADON { get; set; }
        public virtual PHONG PHONG { get; set; }
    }
}
