//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPT
    {
        public int MACTPT { get; set; }
        public Nullable<int> MAKHACHHANG { get; set; }
        public int MAPHIEUTHUE { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual PHIEUTHUE PHIEUTHUE { get; set; }
    }
}
