//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp2
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOAIPHONG
    {
        public string MALOAIPHONG { get; set; }
        public string TENLOAIPHONG { get; set; }
        public int DONGIA { get; set; }
    
        public virtual PHONG PHONG { get; set; }
    }
}
